### ISSUE TITLE
Mod loading error

### ISSUE THREAD

**Issue by Muggo67** [Cy4Shot/Modding-Tutorial-1.18#1]
Hi, 
I was following the tutorial for making the mod in 1.18, since this is my first time doing anything related to Minecraft modding, and I was running into this loading error. I'm not sure if anyone can help me on this or not, but any help would be appreciated.

**Comment by Cy4Shot** [comment]
Hi! I'm gonna close this issue but feel free to ask on our discord! There's a link in the description of each YouTube video. :D

**Comment by Muggo67** [comment]
Ok thank you so much!
